# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)

print(A.shape)

print(A.size)

print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print(B - C)
print()
print(B * C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Exponentiate each number elementwise (use the np.exp function).
print(np.exp(B))

# Calculate the minimum value in the whole matrix. 
print(B.min)

# Calculcate the minimum value in each row.
B.min(axis=1)

print(B.min(axis=1))
      
# Calculcate the minimum value in each column.
B.min(axis=0)
print(B.min(axis=0))

# Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
print(np.argmin(B))

# Find the index value for the minimum value in each row (hint: use np.argmin).
row_min = np.argmin(B, axis=1)
print(row_min)

print(B.argmin(axis=1)) # Ska inte svaret bli [1, 4, 7] istället för [0 0 0]?

B.argmin(axis=1) # array([0, 0, 0])

# Calculate the sum for all elements.
print(B.sum(axis=None, dtype=None, out=None)) # Answer: 45

# Calculate the mean for each column.
print(B.mean(axis=0, dtype=None, out=None)) # the average of all columns: [4. 5. 6.]

# Calculate the median for each column.
print(np.median(B, axis=1)) # [2. 5. 8.]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
<built-in method min of numpy.ndarray object at 0x000001A5136952F0>
[1 4 7]
[1 2 3]
0
[0 0 0]
[0 0 0]
45
[4. 5. 6.]
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
a = np.arange(30) # Creates a one-dimensional array a containing integers from 0 to 29 (a total of 30 elements).
b = a.reshape((2, 3, -1)) # Reshapes the array a into a new array b with three dimensions (or axes).

# Arguments in reshape:
    # First dimension: 2
    # Second dimension: 3
    # Third dimension: -1 (automatically calculated based on the total number of elements).
# Since the array has 30 elements in total, and the first two dimensions are specified as 2 and 3, the third dimension must be 5 (because 30÷(2×3)=5 
# Result: The array is reshaped into size (2,3,5) which means: 
# 2 "blocks": Each block contains 3 rows: 
# Each row contains 5 elements

print(a) # a is printed as a standard one-dimensional array.
print(b) # b is printed as a three-dimensional array with shape (2,3,5).

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


B has three axes because of when you call reshape with more dimensions than the original array, it creates a new array with the specified dimensions. In the case above, three dimensions were requested: 2 "blocks"where each block contains 3 rows and each row contains 5 elements.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [20]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [3]:
def add_mult_matrices(matrix1, matrix2, operation):
    # Validate inputs are of type numpy.ndarray
    if not isinstance(matrix1, np.ndarray):
        raise TypeError("matrix1 must be a numpy.ndarray")
    if not isinstance(matrix2, np.ndarray):
        raise TypeError("matrix2 must be a numpy.ndarray")
    
    # Validate the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("operation must be 'add' or 'multiply'")
    
    if operation == 'add':
        # Validate that the matrices have the same size
        if matrix1.shape != matrix2.shape:
            raise ValueError("For addition, both matrices must have the same shape")
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        # Validate that the sizes conform for multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, the number of columns in matrix1 must equal the number of rows in matrix2")
        return matrix1 @ matrix2
    
# Test matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Addition
result_add = add_mult_matrices(matrix1, matrix2, 'add')
print("Addition Result:\n", result_add)

print()

# Multiplication
result_mult = add_mult_matrices(matrix1, matrix2, 'multiply')
print("Multiplication Result:\n", result_mult)



Addition Result:
 [[ 6  8]
 [10 12]]

Multiplication Result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

### Uppgift10.1.1. ### 

# Definiera vektorn x enligt nedan #

 x=(4,3)

 (a) Vilken dimension har vektorn x?
 (b) Beräkna 5x
 (c) Beräkna 3x
 (d) Beräkna 5x + 3x
 (e) Beräkna 8x
 (f) Beräkna 4x − x
 (g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringenutförts?
 (h) Är x + x⊤ definierat?
 (i) Beräkna ∥x∥

In [21]:
x = np.array([4, 3])

# (a: Vilken dimension har vektorn x?) Svar: x har dimensionen (2,) vilket innebär en vektor med två element
dimension = x.shape
print("Dimension av x:", dimension)

# (b: Beräkna 5x) Svar: 5x = [20 15]
result_b = 5 * x
print("5x:", result_b)

# (c: Beräkna 3x) Svar: 3x = [12,9]
result_c = 3 * x
print("3x:", result_c)

# (d: Beräkna 5x + 3x) Svar: 5x + 3x = [32,24]
result_d = 5 * x + 3 * x
print("5x + 3x:", result_d)

# (e: Beräkna 8x) Svar: 8x = [32, 24]
result_e = 8 * x
print("8x:", result_e)

# (f: Beräkna 4x − x) Svar: 4x - x = [12,9]
result_f = 4 * x - x
print("4x - x:", result_f)

# (g: Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförts?) Svar: 
x_transpose = x.reshape(-1, 1)
print("x^T:\n", x_transpose)
print("Ny dimension efter transponering:", x_transpose.shape)

# (h: Är x + x⊤ definierat?) Svar: Nej, eftersom matriserna har olika dimensioner.

# (i: Beräkna ∥x∥) Svar: 5
print("∥x∥", np.linalg.norm(x))


Dimension av x: (2,)
5x: [20 15]
3x: [12  9]
5x + 3x: [32 24]
8x: [32 24]
4x - x: [12  9]
x^T:
 [[4]
 [3]]
Ny dimension efter transponering: (2, 1)
∥x∥ 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [43]:
# Uppgift 10.2.1
# Definiera matriserna:

import numpy as np

# Definiera matriserna där np.array() skapar en matris från en lista med listor.
# Matrisdimensionerna beror på antalet rader och kolumner i den inre listan

A = np.array([[2, 1, -1],
              [1, -1, 1]])
print("Matrix A:")
print(A)

B = np.array([[4, -2, 1],
              [2, -4, -2]])
print("\nMatrix B:")
print(B)

C = np.array([[1, 2],
              [2, 1]])
print("\nMatrix C:")
print(C)

D = np.array([[3, 4],
              [4, 3]])
print("\nMatrix D:")
print(D)

E = np.array([[1],
              [2]])
print("\nMatrix E:")
print(E)

I = np.array([[1, 0],
              [0, 1]]) # Identitetsmatrisen I definieras som en kvadratisk matris med 1:or längs diagonalen och 0:or på andra platser.
print("\nIdentity Matrix I:")
print(I)
print()


# Utför följande beräkningar:

# (a) 2A
print("a:", 2 * A)
print()

# (b) B −2A
print("b:", B - 2 * A)
print()

# (c) 3C − 2E Svar: odefinierat pga olika dimensioner i matriser

# (d) 2D −3C
print("d:", 2 * D - 3 * C)
print()

# (e) D⊤ +2D
print("e:", np.transpose(D) + 2 * D)
print()

# (f) 2C⊤ −2D⊤
print("f:", 2 * np.transpose(C) - 2 * np.transpose(D))
print()

# (g) A⊤ −B Svar: Inte definerat eftersom A är transponerad

# (h) AC Svar: odefinerat, kolumner i den första matrisen måste vara samma som antal rader i den andra matrisen.

# (i) CD
print("i:", C @ D)
print()

# (j) CB 
print("j:", C @ B)
print()

# (k) CI Identitetsmatris motsvarar att multiplicera med talet 1
print("k:", C @ I)
print()

# (l) ABT
print("l:", A @ np.transpose(B))


Matrix A:
[[ 2  1 -1]
 [ 1 -1  1]]

Matrix B:
[[ 4 -2  1]
 [ 2 -4 -2]]

Matrix C:
[[1 2]
 [2 1]]

Matrix D:
[[3 4]
 [4 3]]

Matrix E:
[[1]
 [2]]

Identity Matrix I:
[[1 0]
 [0 1]]

a: [[ 4  2 -2]
 [ 2 -2  2]]

b: [[ 0 -4  3]
 [ 0 -2 -4]]

d: [[3 2]
 [2 3]]

e: [[ 9 12]
 [12  9]]

f: [[-4 -4]
 [-4 -4]]

i: [[11 10]
 [10 11]]

j: [[  8 -10  -3]
 [ 10  -8   0]]

k: [[1 2]
 [2 1]]

l: [[5 2]
 [7 4]]


In [46]:
# Uppgift 10.2.2

A = np.array([[2, 3, 4],
              [5, 4, 1]])
print("Matrix A:")
print(A)
print()

print(A @ np.transpose(A))

Matrix A:
[[2 3 4]
 [5 4 1]]

[[29 26]
 [26 42]]


In [6]:
 # Uppgift 10.2.3

A = np.array([[1, 2],
              [2, 4]])
print("Matrix A:")
print(A)
print()

B = np.array([[2, 1],
              [1, 3]])
print("Matrix B:")
print(B)
print()

C = np.array([[4, 3],
              [0, 2]])
print("Matrix C:")
print(C)
print()

print("Resultat av AB:", A @ B)             # Svar: [4, 7][8, 14]
print("\nResultat av AC:", A @ C)           # Svar: [4, 7][8, 14]
print("\nAB = AC?", np.all(A @ B == A @ C)) # Svar: True
print("\nResultat av BC;", B @ C)           # Svar: [8, 8][4, 9]
print("\nB = C?", np.all(B == C))           # Svar: False

Matrix A:
[[1 2]
 [2 4]]

Matrix B:
[[2 1]
 [1 3]]

Matrix C:
[[4 3]
 [0 2]]

Resultat av AB: [[ 4  7]
 [ 8 14]]

Resultat av AC: [[ 4  7]
 [ 8 14]]

AB = AC? True

Resultat av BC; [[8 8]
 [4 9]]

B = C? False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [60]:
v1 = np.arange(4)
v2 = v1[-2:] # creates a view
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [61]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [62]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
